// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import type { LegislationServiceGetLegislativeItemsData, LegislationServiceGetLegislativeItemsResponse, LegislationServiceGetLegislativeItemData, LegislationServiceGetLegislativeItemResponse, LegislationServiceGetLegislativeItemError, LegislationServiceCreateLegislativeItemData, LegislationServiceCreateLegislativeItemResponse, LegislationServiceCreateLegislativeItemError, LegislationServiceUpdateLegislativeItemData, LegislationServiceUpdateLegislativeItemResponse, LegislationServiceUpdateLegislativeItemError, LegislationServiceGetLegislativeItemsByCategoryData, LegislationServiceGetLegislativeItemsByCategoryResponse, LegislationServiceGetLegislativeItemsByCategoryError, FeedbackServiceSubmitFeedbackData, FeedbackServiceSubmitFeedbackResponse, FeedbackServiceSubmitFeedbackError, FeedbackServiceGetFeedbackForItemData, FeedbackServiceGetFeedbackForItemResponse, FeedbackServiceGetFeedbackForItemError, FeedbackServiceGetUserFeedbackData, FeedbackServiceGetUserFeedbackResponse, FeedbackServiceModerateFeedbackData, FeedbackServiceModerateFeedbackResponse, FeedbackServiceModerateFeedbackError, FeedbackServiceGetAllFeedbackForModerationData, FeedbackServiceGetAllFeedbackForModerationResponse, VotingServiceToggleVoteData, VotingServiceToggleVoteResponse, VotingServiceToggleVoteError, VotingServiceCheckUserVoteData, VotingServiceCheckUserVoteResponse, VotingServiceCheckUserVoteError, VotingServiceGetUserVotesData, VotingServiceGetUserVotesResponse, VotingServiceGetUserVotesError, VotingServiceGetVoteCountData, VotingServiceGetVoteCountResponse, VotingServiceGetVoteCountError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

/**
 * Legislation Service Get Legislative Items
 * Get all active legislative items.
 */
export const legislationServiceGetLegislativeItems = <ThrowOnError extends boolean = false>(options?: Options<LegislationServiceGetLegislativeItemsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LegislationServiceGetLegislativeItemsResponse, unknown, ThrowOnError>({
        url: '/api/legislation_service/get_legislative_items',
        ...options
    });
};

/**
 * Legislation Service Get Legislative Item
 * Get a specific legislative item by ID.
 */
export const legislationServiceGetLegislativeItem = <ThrowOnError extends boolean = false>(options: Options<LegislationServiceGetLegislativeItemData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LegislationServiceGetLegislativeItemResponse, LegislationServiceGetLegislativeItemError, ThrowOnError>({
        url: '/api/legislation_service/get_legislative_item',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Legislation Service Create Legislative Item
 * Create a new legislative item. Admin only function.
 */
export const legislationServiceCreateLegislativeItem = <ThrowOnError extends boolean = false>(options: Options<LegislationServiceCreateLegislativeItemData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LegislationServiceCreateLegislativeItemResponse, LegislationServiceCreateLegislativeItemError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/legislation_service/create_legislative_item',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Legislation Service Update Legislative Item
 * Update a legislative item. Admin only function.
 */
export const legislationServiceUpdateLegislativeItem = <ThrowOnError extends boolean = false>(options: Options<LegislationServiceUpdateLegislativeItemData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LegislationServiceUpdateLegislativeItemResponse, LegislationServiceUpdateLegislativeItemError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/legislation_service/update_legislative_item',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Legislation Service Get Legislative Items By Category
 * Get all active legislative items in a specific category.
 */
export const legislationServiceGetLegislativeItemsByCategory = <ThrowOnError extends boolean = false>(options: Options<LegislationServiceGetLegislativeItemsByCategoryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LegislationServiceGetLegislativeItemsByCategoryResponse, LegislationServiceGetLegislativeItemsByCategoryError, ThrowOnError>({
        url: '/api/legislation_service/get_legislative_items_by_category',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Feedback Service Submit Feedback
 * Submit feedback on a legislative item.
 */
export const feedbackServiceSubmitFeedback = <ThrowOnError extends boolean = false>(options: Options<FeedbackServiceSubmitFeedbackData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<FeedbackServiceSubmitFeedbackResponse, FeedbackServiceSubmitFeedbackError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/feedback_service/submit_feedback',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Feedback Service Get Feedback For Item
 * Get all approved feedback for a legislative item with vote counts and user emails.
 */
export const feedbackServiceGetFeedbackForItem = <ThrowOnError extends boolean = false>(options: Options<FeedbackServiceGetFeedbackForItemData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<FeedbackServiceGetFeedbackForItemResponse, FeedbackServiceGetFeedbackForItemError, ThrowOnError>({
        url: '/api/feedback_service/get_feedback_for_item',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Feedback Service Get User Feedback
 * Get all feedback submitted by the current user with vote counts.
 */
export const feedbackServiceGetUserFeedback = <ThrowOnError extends boolean = false>(options?: Options<FeedbackServiceGetUserFeedbackData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<FeedbackServiceGetUserFeedbackResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/feedback_service/get_user_feedback',
        ...options
    });
};

/**
 * Feedback Service Moderate Feedback
 * Moderate feedback (admin only). Actions: &#39;approve&#39;, &#39;hide&#39;, &#39;delete&#39;.
 */
export const feedbackServiceModerateFeedback = <ThrowOnError extends boolean = false>(options: Options<FeedbackServiceModerateFeedbackData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<FeedbackServiceModerateFeedbackResponse, FeedbackServiceModerateFeedbackError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/feedback_service/moderate_feedback',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Feedback Service Get All Feedback For Moderation
 * Get all feedback for moderation purposes (admin only).
 */
export const feedbackServiceGetAllFeedbackForModeration = <ThrowOnError extends boolean = false>(options?: Options<FeedbackServiceGetAllFeedbackForModerationData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<FeedbackServiceGetAllFeedbackForModerationResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/feedback_service/get_all_feedback_for_moderation',
        ...options
    });
};

/**
 * Voting Service Toggle Vote
 * Toggle a vote on feedback. Returns the new vote status and count.
 */
export const votingServiceToggleVote = <ThrowOnError extends boolean = false>(options: Options<VotingServiceToggleVoteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<VotingServiceToggleVoteResponse, VotingServiceToggleVoteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/voting_service/toggle_vote',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Voting Service Check User Vote
 * Check if user has voted on specific feedback.
 */
export const votingServiceCheckUserVote = <ThrowOnError extends boolean = false>(options: Options<VotingServiceCheckUserVoteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<VotingServiceCheckUserVoteResponse, VotingServiceCheckUserVoteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/voting_service/check_user_vote',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Voting Service Get User Votes
 * Get user&#39;s vote status for multiple feedback items.
 */
export const votingServiceGetUserVotes = <ThrowOnError extends boolean = false>(options: Options<VotingServiceGetUserVotesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<VotingServiceGetUserVotesResponse, VotingServiceGetUserVotesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/voting_service/get_user_votes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Voting Service Get Vote Count
 * Get the total vote count for a specific feedback.
 */
export const votingServiceGetVoteCount = <ThrowOnError extends boolean = false>(options: Options<VotingServiceGetVoteCountData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<VotingServiceGetVoteCountResponse, VotingServiceGetVoteCountError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/voting_service/get_vote_count',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};