// This file is auto-generated by @hey-api/openapi-ts

export type BodyFeedbackServiceGetFeedbackForItem = {
    legislative_item_id: string;
    sort_by: string;
};

export type BodyFeedbackServiceModerateFeedback = {
    feedback_id: string;
    action: string;
};

export type BodyFeedbackServiceSubmitFeedback = {
    legislative_item_id: string;
    content: string;
};

export type BodyLegislationServiceCreateLegislativeItem = {
    title: string;
    summary: string;
    author: string;
    status: string;
    full_description: string;
    bill_number?: string | null;
    category?: string | null;
};

export type BodyLegislationServiceGetLegislativeItem = {
    item_id: string;
};

export type BodyLegislationServiceGetLegislativeItemsByCategory = {
    category: string;
};

export type BodyLegislationServiceUpdateLegislativeItem = {
    item_id: string;
    title?: string | null;
    summary?: string | null;
    author?: string | null;
    status?: string | null;
    full_description?: string | null;
    bill_number?: string | null;
    category?: string | null;
    is_active?: boolean | null;
};

export type BodyVotingServiceCheckUserVote = {
    feedback_id: string;
};

export type BodyVotingServiceGetUserVotes = {
    feedback_ids: Array<string>;
};

export type BodyVotingServiceGetVoteCount = {
    feedback_id: string;
};

export type BodyVotingServiceToggleVote = {
    feedback_id: string;
};

export type Feedback = {
    id?: string;
    content: string;
    user_id: string;
    legislative_item_id: string;
    status?: string;
    created_at?: string;
    updated_at?: string;
    vote_count?: number;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LegislativeItem = {
    id?: string;
    title: string;
    summary: string;
    author: string;
    status: string;
    full_description: string;
    bill_number?: string | null;
    category?: string | null;
    created_at?: string;
    updated_at?: string;
    is_active?: boolean;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type LegislationServiceGetLegislativeItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/legislation_service/get_legislative_items';
};

export type LegislationServiceGetLegislativeItemsResponses = {
    /**
     * Successful Response
     */
    200: Array<LegislativeItem>;
};

export type LegislationServiceGetLegislativeItemsResponse = LegislationServiceGetLegislativeItemsResponses[keyof LegislationServiceGetLegislativeItemsResponses];

export type LegislationServiceGetLegislativeItemData = {
    body: BodyLegislationServiceGetLegislativeItem;
    path?: never;
    query?: never;
    url: '/api/legislation_service/get_legislative_item';
};

export type LegislationServiceGetLegislativeItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegislationServiceGetLegislativeItemError = LegislationServiceGetLegislativeItemErrors[keyof LegislationServiceGetLegislativeItemErrors];

export type LegislationServiceGetLegislativeItemResponses = {
    /**
     * Successful Response
     */
    200: LegislativeItem | null;
};

export type LegislationServiceGetLegislativeItemResponse = LegislationServiceGetLegislativeItemResponses[keyof LegislationServiceGetLegislativeItemResponses];

export type LegislationServiceCreateLegislativeItemData = {
    body: BodyLegislationServiceCreateLegislativeItem;
    path?: never;
    query?: never;
    url: '/api/legislation_service/create_legislative_item';
};

export type LegislationServiceCreateLegislativeItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegislationServiceCreateLegislativeItemError = LegislationServiceCreateLegislativeItemErrors[keyof LegislationServiceCreateLegislativeItemErrors];

export type LegislationServiceCreateLegislativeItemResponses = {
    /**
     * Successful Response
     */
    200: LegislativeItem;
};

export type LegislationServiceCreateLegislativeItemResponse = LegislationServiceCreateLegislativeItemResponses[keyof LegislationServiceCreateLegislativeItemResponses];

export type LegislationServiceUpdateLegislativeItemData = {
    body: BodyLegislationServiceUpdateLegislativeItem;
    path?: never;
    query?: never;
    url: '/api/legislation_service/update_legislative_item';
};

export type LegislationServiceUpdateLegislativeItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegislationServiceUpdateLegislativeItemError = LegislationServiceUpdateLegislativeItemErrors[keyof LegislationServiceUpdateLegislativeItemErrors];

export type LegislationServiceUpdateLegislativeItemResponses = {
    /**
     * Successful Response
     */
    200: LegislativeItem | null;
};

export type LegislationServiceUpdateLegislativeItemResponse = LegislationServiceUpdateLegislativeItemResponses[keyof LegislationServiceUpdateLegislativeItemResponses];

export type LegislationServiceGetLegislativeItemsByCategoryData = {
    body: BodyLegislationServiceGetLegislativeItemsByCategory;
    path?: never;
    query?: never;
    url: '/api/legislation_service/get_legislative_items_by_category';
};

export type LegislationServiceGetLegislativeItemsByCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegislationServiceGetLegislativeItemsByCategoryError = LegislationServiceGetLegislativeItemsByCategoryErrors[keyof LegislationServiceGetLegislativeItemsByCategoryErrors];

export type LegislationServiceGetLegislativeItemsByCategoryResponses = {
    /**
     * Successful Response
     */
    200: Array<LegislativeItem>;
};

export type LegislationServiceGetLegislativeItemsByCategoryResponse = LegislationServiceGetLegislativeItemsByCategoryResponses[keyof LegislationServiceGetLegislativeItemsByCategoryResponses];

export type FeedbackServiceSubmitFeedbackData = {
    body: BodyFeedbackServiceSubmitFeedback;
    path?: never;
    query?: never;
    url: '/api/feedback_service/submit_feedback';
};

export type FeedbackServiceSubmitFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FeedbackServiceSubmitFeedbackError = FeedbackServiceSubmitFeedbackErrors[keyof FeedbackServiceSubmitFeedbackErrors];

export type FeedbackServiceSubmitFeedbackResponses = {
    /**
     * Successful Response
     */
    200: Feedback;
};

export type FeedbackServiceSubmitFeedbackResponse = FeedbackServiceSubmitFeedbackResponses[keyof FeedbackServiceSubmitFeedbackResponses];

export type FeedbackServiceGetFeedbackForItemData = {
    body: BodyFeedbackServiceGetFeedbackForItem;
    path?: never;
    query?: never;
    url: '/api/feedback_service/get_feedback_for_item';
};

export type FeedbackServiceGetFeedbackForItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FeedbackServiceGetFeedbackForItemError = FeedbackServiceGetFeedbackForItemErrors[keyof FeedbackServiceGetFeedbackForItemErrors];

export type FeedbackServiceGetFeedbackForItemResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type FeedbackServiceGetFeedbackForItemResponse = FeedbackServiceGetFeedbackForItemResponses[keyof FeedbackServiceGetFeedbackForItemResponses];

export type FeedbackServiceGetUserFeedbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/feedback_service/get_user_feedback';
};

export type FeedbackServiceGetUserFeedbackResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type FeedbackServiceGetUserFeedbackResponse = FeedbackServiceGetUserFeedbackResponses[keyof FeedbackServiceGetUserFeedbackResponses];

export type FeedbackServiceModerateFeedbackData = {
    body: BodyFeedbackServiceModerateFeedback;
    path?: never;
    query?: never;
    url: '/api/feedback_service/moderate_feedback';
};

export type FeedbackServiceModerateFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FeedbackServiceModerateFeedbackError = FeedbackServiceModerateFeedbackErrors[keyof FeedbackServiceModerateFeedbackErrors];

export type FeedbackServiceModerateFeedbackResponses = {
    /**
     * Successful Response
     */
    200: boolean;
};

export type FeedbackServiceModerateFeedbackResponse = FeedbackServiceModerateFeedbackResponses[keyof FeedbackServiceModerateFeedbackResponses];

export type FeedbackServiceGetAllFeedbackForModerationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/feedback_service/get_all_feedback_for_moderation';
};

export type FeedbackServiceGetAllFeedbackForModerationResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type FeedbackServiceGetAllFeedbackForModerationResponse = FeedbackServiceGetAllFeedbackForModerationResponses[keyof FeedbackServiceGetAllFeedbackForModerationResponses];

export type VotingServiceToggleVoteData = {
    body: BodyVotingServiceToggleVote;
    path?: never;
    query?: never;
    url: '/api/voting_service/toggle_vote';
};

export type VotingServiceToggleVoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VotingServiceToggleVoteError = VotingServiceToggleVoteErrors[keyof VotingServiceToggleVoteErrors];

export type VotingServiceToggleVoteResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type VotingServiceToggleVoteResponse = VotingServiceToggleVoteResponses[keyof VotingServiceToggleVoteResponses];

export type VotingServiceCheckUserVoteData = {
    body: BodyVotingServiceCheckUserVote;
    path?: never;
    query?: never;
    url: '/api/voting_service/check_user_vote';
};

export type VotingServiceCheckUserVoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VotingServiceCheckUserVoteError = VotingServiceCheckUserVoteErrors[keyof VotingServiceCheckUserVoteErrors];

export type VotingServiceCheckUserVoteResponses = {
    /**
     * Successful Response
     */
    200: boolean;
};

export type VotingServiceCheckUserVoteResponse = VotingServiceCheckUserVoteResponses[keyof VotingServiceCheckUserVoteResponses];

export type VotingServiceGetUserVotesData = {
    body: BodyVotingServiceGetUserVotes;
    path?: never;
    query?: never;
    url: '/api/voting_service/get_user_votes';
};

export type VotingServiceGetUserVotesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VotingServiceGetUserVotesError = VotingServiceGetUserVotesErrors[keyof VotingServiceGetUserVotesErrors];

export type VotingServiceGetUserVotesResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type VotingServiceGetUserVotesResponse = VotingServiceGetUserVotesResponses[keyof VotingServiceGetUserVotesResponses];

export type VotingServiceGetVoteCountData = {
    body: BodyVotingServiceGetVoteCount;
    path?: never;
    query?: never;
    url: '/api/voting_service/get_vote_count';
};

export type VotingServiceGetVoteCountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VotingServiceGetVoteCountError = VotingServiceGetVoteCountErrors[keyof VotingServiceGetVoteCountErrors];

export type VotingServiceGetVoteCountResponses = {
    /**
     * Successful Response
     */
    200: number;
};

export type VotingServiceGetVoteCountResponse = VotingServiceGetVoteCountResponses[keyof VotingServiceGetVoteCountResponses];