# Auto-generated by Lumenary
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Union, Literal, Annotated, Tuple, Set, Any

from datetime import datetime, date, time, timedelta
from uuid import UUID
import uuid

class TokenExchangeRequest(BaseModel):
    client_id: str
    grant_type: str
    code: Optional[str] = None
    code_verifier: Optional[str] = None

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int = 3600

class TokenValidationRequest(BaseModel):
    token: str
    
class LogoutResponse(BaseModel):
    success: bool = True

# Import user-defined models that we need for input/response models
from core.legislative_item import LegislativeItem
from core.feedback import Feedback
from core.vote import Vote
from core.user import User

GetLegislativeItemsOutputSchema = List[LegislativeItem]
class BodyLegislationServiceGetLegislativeItem(BaseModel):
  item_id: UUID

GetLegislativeItemOutputSchema = Optional[LegislativeItem]
class BodyLegislationServiceCreateLegislativeItem(BaseModel):
  title: str
  summary: str
  author: str
  status: str
  full_description: str
  bill_number: Optional[str] = None
  category: Optional[str] = None

CreateLegislativeItemOutputSchema = LegislativeItem
class BodyLegislationServiceUpdateLegislativeItem(BaseModel):
  item_id: UUID
  title: Optional[str] = None
  summary: Optional[str] = None
  author: Optional[str] = None
  status: Optional[str] = None
  full_description: Optional[str] = None
  bill_number: Optional[str] = None
  category: Optional[str] = None
  is_active: Optional[bool] = None

UpdateLegislativeItemOutputSchema = Optional[LegislativeItem]
class BodyLegislationServiceGetLegislativeItemsByCategory(BaseModel):
  category: str

GetLegislativeItemsByCategoryOutputSchema = List[LegislativeItem]
class BodyFeedbackServiceSubmitFeedback(BaseModel):
  legislative_item_id: UUID
  content: str

SubmitFeedbackOutputSchema = Feedback
class BodyFeedbackServiceGetFeedbackForItem(BaseModel):
  legislative_item_id: UUID
  sort_by: str

GetFeedbackForItemOutputSchema = List[dict]
GetUserFeedbackOutputSchema = List[dict]
class BodyFeedbackServiceModerateFeedback(BaseModel):
  feedback_id: UUID
  action: str

ModerateFeedbackOutputSchema = bool
GetAllFeedbackForModerationOutputSchema = List[dict]
class BodyVotingServiceToggleVote(BaseModel):
  feedback_id: UUID

ToggleVoteOutputSchema = dict
class BodyVotingServiceCheckUserVote(BaseModel):
  feedback_id: UUID

CheckUserVoteOutputSchema = bool
class BodyVotingServiceGetUserVotes(BaseModel):
  feedback_ids: List[UUID]

GetUserVotesOutputSchema = dict
class BodyVotingServiceGetVoteCount(BaseModel):
  feedback_id: UUID

GetVoteCountOutputSchema = int
    